### PR TITLE
Markdown

### PR DESCRIPTION
**Pull request by eytanohana**

### CODE REVIEW

**Comment by eytanohana** [comment]
@osherboudara99 
I added in a little thing about circuits to set up for euler circuits. (new PR to come soon)
I also made all the images in the readme aligned to the center except for the first.
I think it looks better aligned left.

**Comment by eytanohana** [comment]
I also added in an image of a connected graph next to the completely connected one and some slight formatting. 
If you think it looks good go ahead and merge otherwise drop me a comment :)

**Comment by osherboudara99** [comment]
Looks good -- change this sentence: "Along with cycles, __circuits__ are a type of cycles where vertices can repeat", maybe just remove the 's' after the second cycles.

**Comment by eytanohana** [comment]
I fixed the sentence and added a bit to cycles . 
I think it looks good. ready to merge @osherboudara99 ?

**Comment by osherboudara99** [comment]
yes merging

**Comment by eytanohana** [comment]
great!

**Pull request merged**
